'use strict';
/**
 * lib/categoryMap.js — SINGLE SOURCE OF TRUTH for category resolution.
 *
 * All paths (web search, voice/SMS, MCP, intentRouter) import from here.
 * Never patch _SVC_MAP, intentMap.js, or intentRouter.js separately again.
 *
 * Covers: top 100 web searches + full slang/casual/typo/conversational variants.
 * "Talk to it like a buddy" — incomplete sentences, bad spelling, dialect all work.
 */

// ── Real DB categories (ground-truthed against businesses table) ──────────────
const DB_CATS = [
  'restaurant','fast_food','hotel','cafe','bank','real_estate','grocery','retail','bar',
  'plumber','landscaping','dental','electrician','beauty_salon','pharmacy','fuel',
  'convenience','beauty','auto_repair','gas_station','clothes','law_firm','general_contractor',
  'dry_cleaning','insurance','insurance_agency','hairdresser','pizza','childcare','supermarket',
  'upscale_hotel','department_store','car_repair','legal','gym','dentist','variety_store',
  'veterinary','coffee_chain','accounting','casual_dining','urgent_care','healthcare',
  'fitness_centre','sports_centre','bakery','doctors','finance','ice_cream','gym_chain',
  'budget_hotel','sports_bar','furniture','mexican','car_parts','jewelry','seafood',
  'barbershop','pub','alcohol','car_rental','museum','shoes','pet','hospital','fitness',
  'estate_agent','chemist','optician','auto_dealer','sandwich','hair_chain','bbq',
  'steakhouse','deli','storage_rental','big_box','real_estate_agency','car_wash','tax_advisor',
  'massage','doityourself','financial_advisor','credit_union','swimming_pool',
  'nutrition_supplements','electronics','hardware','fast_casual_mexican','handyman',
  'florist','laundry','spa_massage','pest_control','locksmith','painting','roofing',
  'hvac','moving','pool_service','concrete','flooring','tattoo','atm','bank_branch',
  'fine_dining','brewery','bar_dining','cosmetics','pet_grooming','medical_spa',
  'aesthetics','plastic_surgery','dermatology','towing','liquor_store','wine',
];

// ── CAT_EXPAND: resolvedCat → exact DB category strings for SQL ANY() match ──
const CAT_EXPAND = {
  // Food & drink
  restaurant:      ['restaurant','fast_food','casual_dining','fine_dining','deli','seafood',
                    'mexican','bbq','steakhouse','sandwich','bar_dining','fast_casual_mexican'],
  pizza:           ['pizza','restaurant','fast_food'],
  bar:             ['bar','pub','sports_bar','brewery','bar_dining','alcohol'],
  cafe:            ['cafe','coffee_chain','bakery','deli','ice_cream'],
  seafood:         ['seafood','restaurant'],
  // Medical / health
  healthcare:      ['clinic','hospital','doctors','dentist','dental','pharmacy','urgent_care',
                    'veterinary','healthcare','optician','fitness_centre'],
  clinic:          ['clinic','doctors','urgent_care','hospital','healthcare'],
  dentist:         ['dentist','dental'],
  pharmacy:        ['pharmacy','chemist'],
  plastic_surgery: ['plastic_surgery','dermatology','medical_spa','aesthetics','doctors','clinic'],
  dermatology:     ['dermatology','medical_spa','aesthetics'],
  // Beauty
  beauty:          ['beauty_salon','hairdresser','barbershop','hair_chain','beauty','cosmetics'],
  beauty_salon:    ['beauty_salon','hairdresser','hair_chain','beauty'],
  nail_salon:      ['nail_salon','nails'],
  nails:           ['nail_salon','nails'],
  spa:             ['spa_massage','massage','beauty_salon'],
  massage:         ['spa_massage','massage'],
  barbershop:      ['barbershop','beauty_salon','hairdresser'],
  // Home services
  plumber:         ['plumber'],
  electrician:     ['electrician'],
  hvac:            ['hvac'],
  handyman:        ['handyman','doityourself','general_contractor'],
  roofing:         ['roofing','general_contractor'],
  landscaping:     ['landscaping','lawn_care','lawn_service','landscaping_contractor'],
  painting:        ['painting'],
  cleaning:        ['dry_cleaning','laundry'],
  dry_cleaning:    ['dry_cleaning','laundry'],
  pest_control:    ['pest_control'],
  locksmith:       ['locksmith'],
  flooring:        ['flooring'],
  pool_service:    ['pool_service','swimming_pool'],
  moving:          ['moving'],
  general_contractor: ['general_contractor'],
  // Auto
  auto_repair:     ['auto_repair','car_repair'],
  auto_dealer:     ['auto_dealer'],
  car_wash:        ['car_wash'],
  car_rental:      ['car_rental'],
  towing:          ['towing'],
  gas_station:     ['gas_station','fuel'],
  // Retail
  retail:          ['retail','clothes','shoes','department_store','furniture','jewelry',
                    'variety_store','big_box','cosmetics','nutrition_supplements','electronics','hardware'],
  clothes:         ['clothes','shoes','department_store','variety_store'],
  grocery:         ['grocery','supermarket','convenience'],
  convenience:     ['convenience','grocery','supermarket'],
  hardware:        ['hardware','doityourself'],
  furniture:       ['furniture','big_box'],
  jewelry:         ['jewelry'],
  electronics:     ['electronics'],
  alcohol:         ['alcohol','liquor_store','wine','bar','pub'],
  // Professional
  law_firm:        ['law_firm','legal','lawyer'],
  accounting:      ['accounting'],
  insurance:       ['insurance','insurance_agency'],
  tax_advisor:     ['tax_advisor','accounting'],
  financial_advisor: ['financial_advisor','finance','accounting'],
  // Finance
  bank:            ['bank','bank_branch','credit_union','atm'],
  finance:         ['financial_advisor','finance','bank','accounting'],
  // Real estate
  real_estate:     ['real_estate','real_estate_agency','estate_agent'],
  // Fitness
  gym:             ['gym','gym_chain','fitness_centre','sports_centre','fitness'],
  // Hospitality
  hotel:           ['hotel','upscale_hotel','budget_hotel'],
  // Pet
  veterinary:      ['veterinary','pet','pet_grooming'],
  // Other services
  florist:         ['florist'],
  tattoo:          ['tattoo'],
  storage:         ['storage_rental'],
  childcare:       ['childcare'],
  optician:        ['optician'],
  museum:          ['museum'],
  // Tech / B2B
  it_services:          ['it_services'],
  network_infrastructure: ['network_infrastructure','it_services'],
  startup_accelerator:  ['startup_accelerator'],
  venture_studio:       ['venture_studio'],
};

// ── Service delivery type: does the provider come TO the customer, or customer goes TO them? ──
//
// COME_TO_ME  → provider travels to customer site → RFQ / bid flow
//               "Would you like to send a bid request to these providers?"
//
// GO_TO_STORE → customer travels to provider → appointment / reservation / menu flow
//               "Would you like to schedule an appointment?" or "View menu" or "Make a reservation"
//
// INFO_ONLY   → no booking needed (bank, real estate, insurance, legal) → show info + contact

const COME_TO_ME_CATS = new Set([
  // Trades / home services
  'plumber','plumbing','electrician','hvac','handyman','roofing','landscaping',
  'painting','pest_control','locksmith','flooring','pool_service','moving',
  'general_contractor','contractor','concrete','cleaning','dry_cleaning',
  // Auto come-to-you
  'towing',
  // Delivery-style
  'catering',
]);

const APPOINTMENT_CATS = new Set([
  // Beauty & personal care (customer goes to them)
  'beauty','beauty_salon','hairdresser','barbershop','hair_chain','nail_salon','nails',
  'spa_massage','massage','spa','cosmetics','tattoo','pet_grooming','optician',
  // Medical (customer goes to them)
  'clinic','dentist','dental','doctors','urgent_care','hospital','healthcare',
  'veterinary','plastic_surgery','dermatology','medical_spa','aesthetics','pharmacy','chemist',
  // Fitness (customer goes to them)
  'gym','gym_chain','fitness_centre','sports_centre','fitness',
  // Childcare
  'childcare',
]);

const RESERVATION_CATS = new Set([
  // Dining (customer goes to them)
  'restaurant','fast_food','casual_dining','fine_dining','cafe','coffee_chain','bakery',
  'pizza','bar','pub','sports_bar','brewery','bar_dining','seafood','mexican','bbq',
  'steakhouse','sandwich','fast_casual_mexican','deli','ice_cream','dessert',
  // Lodging
  'hotel','upscale_hotel','budget_hotel',
]);

/**
 * Returns the CTA type for a resolved category.
 *
 * @param {string} cat  — resolved category key (from KEYWORD_MAP or intentMap)
 * @returns {'rfq' | 'appointment' | 'reservation' | 'menu' | 'info'}
 *
 * rfq         → provider comes to customer — send bid request
 * appointment → customer goes to provider, booking required (beauty, medical, gym)
 * reservation → customer goes to provider, table/booking required (restaurant, hotel)
 * menu        → food/drink venue — show menu / order
 * info        → show info + contact only (retail, grocery, bank, legal, real estate)
 */
function getCTAType(cat) {
  if (!cat) return 'info';
  const c = cat.toLowerCase();
  if (COME_TO_ME_CATS.has(c))   return 'rfq';
  if (RESERVATION_CATS.has(c))  return 'reservation';
  if (APPOINTMENT_CATS.has(c))  return 'appointment';
  return 'info';
}

/**
 * Human-readable prompt text for each CTA type.
 * Used in the service_request narrative shown to the user.
 */
const CTA_PROMPTS = {
  rfq:         'Want me to send your request to these providers and see who can do it?',
  appointment: 'Want to book with any of these? Drop your info and we\'ll send it over.',
  reservation: null,   // reservation — direct to business, no agent mediation
  menu:        null,   // menu — direct to business link
  info:        null,   // no CTA prompt — just show the results
};

// ── KEYWORD_MAP: any query substring → resolvedCat key ─────────────────────────
// ORDER MATTERS — first match wins. Most specific / longest phrases first.
// Lowercase only. Covers: typed search, voice transcript, SMS, MCP.
// Design goal: talk to it like a buddy — casual, misspelled, slang, incomplete all work.
const KEYWORD_MAP = [

  // ══════════════════════════════════════════════════════════════════════════════
  // FOOD & DRINK
  // ══════════════════════════════════════════════════════════════════════════════

  // Hunger / generic food (must be before specific foods)
  ['i need something to eat',  'restaurant'],
  ['something to eat',         'restaurant'],
  ['i need food',              'restaurant'],
  ['need food',                'restaurant'],
  ['i am starving',            'restaurant'],
  ['i am hungry',              'restaurant'],
  ["i'm starving",             'restaurant'],
  ["i'm hungry",               'restaurant'],
  ['im starving',              'restaurant'],
  ['im hungry',                'restaurant'],
  ['where should i eat',       'restaurant'],
  ['where can i eat',          'restaurant'],
  ['where to eat',             'restaurant'],
  ['place to eat',             'restaurant'],
  ['spot to eat',              'restaurant'],
  ['places to eat',            'restaurant'],
  ['food near me',             'restaurant'],
  ['good food',                'restaurant'],
  ['eat out',                  'restaurant'],
  ['eat tonight',              'restaurant'],
  ['grab food',                'restaurant'],
  ['grab a bite',              'restaurant'],
  ['get some food',            'restaurant'],
  ['get a bite',               'restaurant'],
  ['finna eat',                'restaurant'],
  ['tryna eat',                'restaurant'],
  ['tryna find food',          'restaurant'],
  ['want to eat',              'restaurant'],
  ['wanna eat',                'restaurant'],
  ['late night food',          'restaurant'],
  ['late night eats',          'restaurant'],
  ['midnight snack',           'restaurant'],
  ['open late food',           'restaurant'],
  ['what can i eat',           'restaurant'],
  ['hungry as hell',           'restaurant'],
  ['hungry af',                'restaurant'],
  ['need grub',                'restaurant'],
  ['grub near',                'restaurant'],
  ['where do people eat',      'restaurant'],
  ['best restaurant',          'restaurant'],
  ['good restaurant',          'restaurant'],
  ['cheap eats',               'restaurant'],
  ['feed me',                  'restaurant'],
  ['restaurants near',         'restaurant'],
  ['dine in',                  'restaurant'],
  ['sit down restaurant',      'restaurant'],

  // Casual slang food
  ['grub',   'restaurant'],
  ['eats',   'restaurant'],
  ['chow',   'restaurant'],
  ['bussin', 'restaurant'],
  ['slaps',  'restaurant'],
  ['fire food','restaurant'],

  // Specific cuisines
  ['pizza',            'pizza'],
  ['calzone',          'pizza'],
  ['slice',            'pizza'],
  ['pies',             'pizza'],
  ['sushi',            'seafood'],
  ['seafood',          'seafood'],
  ['fish market',      'seafood'],
  ['fresh fish',       'seafood'],
  ['oysters',          'seafood'],
  ['shrimp',           'seafood'],
  ['crab legs',        'seafood'],
  ['lobster',          'seafood'],
  ['ramen',            'restaurant'],
  ['pho',              'restaurant'],
  ['dim sum',          'restaurant'],
  ['chinese food',     'restaurant'],
  ['chinese restaurant','restaurant'],
  ['italian food',     'restaurant'],
  ['italian restaurant','restaurant'],
  ['thai food',        'restaurant'],
  ['thai restaurant',  'restaurant'],
  ['indian food',      'restaurant'],
  ['indian restaurant','restaurant'],
  ['mexican food',     'restaurant'],
  ['tacos',            'restaurant'],
  ['burritos',         'restaurant'],
  ['ethiopian food',   'restaurant'],
  ['korean food',      'restaurant'],
  ['korean bbq',       'restaurant'],
  ['japanese food',    'restaurant'],
  ['greek food',       'restaurant'],
  ['mediterranean food','restaurant'],
  ['vietnamese food',  'restaurant'],
  ['burger',           'restaurant'],
  ['burgers',          'restaurant'],
  ['wings',            'restaurant'],
  ['chicken wings',    'restaurant'],
  ['hot wings',        'restaurant'],
  ['steak',            'restaurant'],
  ['steakhouse',       'restaurant'],
  ['fine dining',      'restaurant'],
  ['brunch',           'restaurant'],
  ['breakfast spot',   'restaurant'],
  ['breakfast place',  'restaurant'],
  ['sandwiches',       'restaurant'],
  ['sub shop',         'restaurant'],
  ['bbq',              'restaurant'],
  ['barbecue',         'restaurant'],
  ['smoked meat',      'restaurant'],
  ['brisket',          'restaurant'],

  // Bar / drinks
  ['happy hour',         'bar'],
  ['cocktails',          'bar'],
  ['nightlife',          'bar'],
  ['craft beer',         'bar'],
  ['brewery',            'bar'],
  ['brewpub',            'bar'],
  ['pregame',            'bar'],
  ['get lit',            'bar'],
  ['bar hop',            'bar'],
  ['vibes tonight',      'bar'],
  ['pull up to the bar', 'bar'],
  ['hit the bar',        'bar'],
  ['night out',          'bar'],
  ['going out tonight',  'bar'],
  ['where to drink',     'bar'],
  ['places to drink',    'bar'],
  ['sports bar',         'bar'],
  ['watch the game',     'bar'],
  ['watch football',     'bar'],
  ['watch the fight',    'bar'],
  ['trivia night',       'bar'],
  ['karaoke',            'bar'],
  ['dive bar',           'bar'],
  ['rooftop bar',        'bar'],

  // Coffee / cafe
  ['coffee',       'cafe'],
  ['espresso',     'cafe'],
  ['latte',        'cafe'],
  ['cappuccino',   'cafe'],
  ['cold brew',    'cafe'],
  ['americano',    'cafe'],
  ['frappuccino',  'cafe'],
  ['bakery',       'cafe'],
  ['pastries',     'cafe'],
  ['bagels',       'cafe'],
  ['donuts',       'cafe'],
  ['doughnuts',    'cafe'],
  ['croissant',    'cafe'],
  ['ice cream',    'cafe'],
  ['froyo',        'cafe'],
  ['frozen yogurt','cafe'],
  ['smoothie',     'cafe'],
  ['juice bar',    'cafe'],
  ['boba',         'cafe'],
  ['bubble tea',   'cafe'],
  ['coffee shop',  'cafe'],
  ['cafe near',    'cafe'],
  ['coffee near',  'cafe'],

  // Alcohol / liquor store (specific before bar)
  ['vodka',              'alcohol'],
  ['whiskey',            'alcohol'],
  ['whisky',             'alcohol'],
  ['tequila',            'alcohol'],
  ['bourbon',            'alcohol'],
  ['rum',                'alcohol'],
  ['gin',                'alcohol'],
  ['brandy',             'alcohol'],
  ['cognac',             'alcohol'],
  ['scotch',             'alcohol'],
  ['hard seltzer',       'alcohol'],
  ['white claw',         'alcohol'],
  ['liquor',             'alcohol'],
  ['booze',              'alcohol'],
  ['beer run',           'alcohol'],
  ['six pack',           'alcohol'],
  ['case of beer',       'alcohol'],
  ['gallon of beer',     'alcohol'],
  ['bottle of wine',     'alcohol'],
  ['wine shop',          'alcohol'],
  ['liquor store',       'alcohol'],
  ['package store',      'alcohol'],
  ['grab a beer',        'alcohol'],
  ['pick up beer',       'alcohol'],
  ['get some beer',      'alcohol'],
  ['buy beer',           'alcohol'],
  ['buy wine',           'alcohol'],
  ['buy vodka',          'alcohol'],
  ['buy booze',          'alcohol'],
  ['buy liquor',         'alcohol'],
  ['buy a bottle',       'alcohol'],
  ['need wine',          'alcohol'],
  ['need beer',          'alcohol'],
  ['need alcohol',       'alcohol'],
  ['need a drink',       'alcohol'],
  ['need liquor',        'alcohol'],
  ['find liquor',        'alcohol'],
  ['where can i get beer','alcohol'],
  ['where can i buy beer','alcohol'],

  // ══════════════════════════════════════════════════════════════════════════════
  // PHARMACY / CONVENIENCE PRODUCTS
  // ══════════════════════════════════════════════════════════════════════════════

  ['toothbrush',      'pharmacy'],
  ['tothbrush',       'pharmacy'],  // typo
  ['tooth brush',     'pharmacy'],
  ['toothpaste',      'pharmacy'],
  ['tooth paste',     'pharmacy'],
  ['tothpaste',       'pharmacy'],  // typo
  ['deodorant',       'pharmacy'],
  ['deodarant',       'pharmacy'],  // typo
  ['deodrant',        'pharmacy'],  // typo
  ['deodoran',        'pharmacy'],  // typo
  ['deodarent',       'pharmacy'],  // typo
  ['body spray',      'pharmacy'],
  ['antiperspirant',  'pharmacy'],
  ['shampoo',         'pharmacy'],
  ['conditioner',     'pharmacy'],
  ['body wash',       'pharmacy'],
  ['face wash',       'pharmacy'],
  ['lotion',          'pharmacy'],
  ['moisturizer',     'pharmacy'],
  ['sunscreen',       'pharmacy'],
  ['sunblock',        'pharmacy'],
  ['razor',           'pharmacy'],
  ['razors',          'pharmacy'],
  ['band aid',        'pharmacy'],
  ['bandage',         'pharmacy'],
  ['first aid',       'pharmacy'],
  ['q tip',           'pharmacy'],
  ['qtip',            'pharmacy'],
  ['nail clippers',   'pharmacy'],
  ['tylenol',         'pharmacy'],
  ['advil',           'pharmacy'],
  ['ibuprofen',       'pharmacy'],
  ['aspirin',         'pharmacy'],
  ['nyquil',          'pharmacy'],
  ['dayquil',         'pharmacy'],
  ['cough syrup',     'pharmacy'],
  ['cough drops',     'pharmacy'],
  ['cold meds',       'pharmacy'],
  ['cold medicine',   'pharmacy'],
  ['allergy meds',    'pharmacy'],
  ['allergy medicine','pharmacy'],
  ['antacid',         'pharmacy'],
  ['tums',            'pharmacy'],
  ['pepto',           'pharmacy'],
  ['peptobismol',     'pharmacy'],
  ['melatonin',       'pharmacy'],
  ['vitamins',        'pharmacy'],
  ['condoms',         'pharmacy'],
  ['drug store',      'pharmacy'],
  ['drugstore',       'pharmacy'],
  ['walgreens',       'pharmacy'],
  ['cvs',             'pharmacy'],
  ['rite aid',        'pharmacy'],

  // Convenience / snacks
  ['toilet paper',    'convenience'],
  ['tp',              'convenience'],
  ['paper towel',     'convenience'],
  ['paper towels',    'convenience'],
  ['tissues',         'convenience'],
  ['kleenex',         'convenience'],
  ['trash bags',      'convenience'],
  ['garbage bags',    'convenience'],
  ['doritos',         'convenience'],
  ['chips',           'convenience'],
  ['snacks',          'convenience'],
  ['candy',           'convenience'],
  ['gum',             'convenience'],
  ['soda',            'convenience'],
  ['energy drink',    'convenience'],
  ['red bull',        'convenience'],
  ['monster energy',  'convenience'],
  ['gatorade',        'convenience'],
  ['water bottles',   'convenience'],
  ['phone charger',   'convenience'],
  ['batteries',       'convenience'],
  ['light bulb',      'convenience'],
  ['lightbulb',       'convenience'],
  ['extension cord',  'convenience'],
  ['tape',            'convenience'],
  ['super glue',      'convenience'],
  ['lighter',         'convenience'],
  ['matches',         'convenience'],
  ['corner store',    'convenience'],
  ['bodega',          'convenience'],
  ['7 eleven',        'convenience'],
  ['7-eleven',        'convenience'],
  ['convenience store','convenience'],

  // ══════════════════════════════════════════════════════════════════════════════
  // BEAUTY & WELLNESS
  // ══════════════════════════════════════════════════════════════════════════════

  // Hair
  ['hair done',         'beauty'],
  ['hair did',          'beauty'],
  ['hair styled',       'beauty'],
  ['get my hair',       'beauty'],
  ['do my hair',        'beauty'],
  ['hair appointment',  'beauty'],
  ['blowout',           'beauty'],
  ['highlights',        'beauty'],
  ['balayage',          'beauty'],
  ['color my hair',     'beauty'],
  ['dye my hair',       'beauty'],
  ['hair color',        'beauty'],
  ['haircut',           'beauty'],
  ['haricut',           'beauty'],  // typo
  ['haircutt',          'beauty'],  // typo
  ['hairkut',           'beauty'],  // typo
  ['hair cut',          'beauty'],
  ['need a cut',        'beauty'],
  ['get a cut',         'beauty'],
  ['need a trim',       'beauty'],
  ['get a trim',        'beauty'],
  ['trim my hair',      'beauty'],
  ['cut my hair',       'beauty'],
  ['fade',              'beauty'],
  ['lineup',            'beauty'],
  ['fresh cut',         'beauty'],
  ['shape up',          'beauty'],
  ['shape-up',          'beauty'],
  ['jit needs a cut',   'beauty'],
  ['get lined up',      'beauty'],
  ['need a fade',       'beauty'],
  ['want a fade',       'beauty'],
  ['taper fade',        'beauty'],
  ['buzz cut',          'beauty'],
  ['hair salon',        'beauty'],
  ['salon near',        'beauty'],
  ['beauty salon',      'beauty'],

  // Nails
  ['nails done',   'nail_salon'],
  ['nails did',    'nail_salon'],
  ['get my nails', 'nail_salon'],
  ['do my nails',  'nail_salon'],
  ['manicure',     'nail_salon'],
  ['pedicure',     'nail_salon'],
  ['nail salon',   'nail_salon'],
  ['nail shop',    'nail_salon'],
  ['nail place',   'nail_salon'],
  ['nails place',  'nail_salon'],
  ['mani pedi',    'nail_salon'],
  ['mani-pedi',    'nail_salon'],
  ['mani',         'nail_salon'],
  ['acrylic nails','nail_salon'],
  ['acrylic set',  'nail_salon'],
  ['nail fill',    'nail_salon'],
  ['infill',       'nail_salon'],
  ['dip nails',    'nail_salon'],
  ['dip powder',   'nail_salon'],
  ['nail extensions','nail_salon'],
  ['press-on nails','nail_salon'],
  ['nail appointment','nail_salon'],
  ['nail tech',    'nail_salon'],
  ['nail art',     'nail_salon'],
  ['where can i get my nails','nail_salon'],
  ['nails',        'nail_salon'],
  ['nail',         'nail_salon'],
  ['nail salon',   'nail_salon'],
  ['acrylics',     'beauty'],
  ['gel nails',    'nail_salon'],
  ['gel polish',   'nail_salon'],
  ['set of nails', 'nail_salon'],

  // Eyebrows / lashes / wax
  ['wax',            'beauty'],
  ['waxing',         'beauty'],
  ['threading',      'beauty'],
  ['eyebrows',       'beauty'],
  ['eyebrow tint',   'beauty'],
  ['lash extensions','beauty'],
  ['lashes done',    'beauty'],
  ['lash lift',      'beauty'],
  ['brow lamination','beauty'],

  // Barber (specific — before beauty catch-all)
  ['barber',       'barbershop'],
  ['barbershop',   'barbershop'],
  ['barber shop',  'barbershop'],
  ['barber near',  'barbershop'],
  ['find a barber','barbershop'],
  ['need a barber','barbershop'],
  ['get a barber', 'barbershop'],
  ['where to get a haircut','barbershop'],

  // Spa / massage
  ['massage',          'massage'],
  ['deep tissue',      'massage'],
  ['swedish massage',  'massage'],
  ['hot stone',        'massage'],
  ['sports massage',   'massage'],
  ['body massage',     'massage'],
  ['get a massage',    'massage'],
  ['need a massage',   'massage'],
  ['spa',              'spa'],
  ['facial',           'spa'],
  ['skin treatment',   'spa'],
  ['day spa',          'spa'],
  ['spa day',          'spa'],
  ['relaxation',       'spa'],
  ['pamper',           'spa'],
  ['self care',        'spa'],

  // ══════════════════════════════════════════════════════════════════════════════
  // HOME SERVICES
  // ══════════════════════════════════════════════════════════════════════════════

  // Plumber
  ['plumber',         'plumber'],
  ['plumbing',        'plumber'],
  ['plumbr',          'plumber'],  // typo
  ['pipe burst',      'plumber'],
  ['burst pipe',      'plumber'],
  ['leaking pipe',    'plumber'],
  ['water leak',      'plumber'],
  ['leak',            'plumber'],
  ['drain clogged',   'plumber'],
  ['clogged drain',   'plumber'],
  ['drain is clogged','plumber'],
  ['toilet clogged',  'plumber'],
  ['toilet wont flush','plumber'],
  ['toilet is broken','plumber'],
  ['water heater',    'plumber'],
  ['faucet',          'plumber'],
  ['faucet dripping', 'plumber'],
  ['pipes',           'plumber'],
  ['pipes messed up', 'plumber'],
  ['sewage',          'plumber'],
  ['sewer',           'plumber'],
  ['no hot water',    'plumber'],
  ['low water pressure','plumber'],
  ['flooded bathroom','plumber'],

  // Electrician
  ['electrician',       'electrician'],
  ['electrical',        'electrician'],
  ['wiring',            'electrician'],
  ['outlet',            'electrician'],
  ['breaker',           'electrician'],
  ['circuit breaker',   'electrician'],
  ['no power',          'electrician'],
  ['power is out',      'electrician'],
  ['lights wont turn on','electrician'],
  ['flickering lights', 'electrician'],
  ['panel upgrade',     'electrician'],
  ['electrical panel',  'electrician'],
  ['electric work',     'electrician'],

  // HVAC
  ['hvac',              'hvac'],
  ['air conditioning',  'hvac'],
  ['air conditioner',   'hvac'],
  ['ac broken',         'hvac'],
  ['ac is broken',      'hvac'],
  ['ac stopped',        'hvac'],
  ['ac went out',       'hvac'],
  ['ac not working',    'hvac'],
  ['ac is out',         'hvac'],
  ['ac is not working', 'hvac'],
  ['my ac',             'hvac'],
  ['heat pump',         'hvac'],
  ['furnace',           'hvac'],
  ['heater',            'hvac'],
  ['heat not working',  'hvac'],
  ['duct cleaning',     'hvac'],
  ['ac tune up',        'hvac'],
  ['ac unit',           'hvac'],
  ['central air',       'hvac'],
  ['its too hot in here','hvac'],
  ['too cold in here',  'hvac'],

  // Landscaping
  ['landscaping',     'landscaping'],
  ['landscaper',      'landscaping'],
  ['lawn',            'landscaping'],
  ['mow',             'landscaping'],
  ['mowing',          'landscaping'],
  ['yard work',       'landscaping'],
  ['yard service',    'landscaping'],
  ['tree trimming',   'landscaping'],
  ['tree service',    'landscaping'],
  ['tree removal',    'landscaping'],
  ['cut my grass',    'landscaping'],
  ['cut the grass',   'landscaping'],
  ['cut my lawn',     'landscaping'],
  ['grass too high',  'landscaping'],
  ['mulch',           'landscaping'],
  ['irrigation',      'landscaping'],
  ['sprinkler',       'landscaping'],
  ['sod',             'landscaping'],
  ['hedge',           'landscaping'],
  ['bushes trimmed',  'landscaping'],
  ['stump removal',   'landscaping'],
  ['stump grinding',  'landscaping'],
  ['arborist',        'landscaping'],
  ['lawn care',       'landscaping'],
  ['lawn service',    'landscaping'],
  // Landscaping slang / outdoor living (Florida-specific)
  ['screened lanai',   'landscaping'],
  ['lanai',            'landscaping'],
  ['pool cage',        'landscaping'],
  ['screen enclosure', 'landscaping'],
  ['paver patio',      'landscaping'],
  ['backyard glow up', 'landscaping'],
  ['backyard glow-up', 'landscaping'],
  ['backyard oasis',   'landscaping'],
  ['backyard makeover','landscaping'],
  ['full yard refresh','landscaping'],
  ['outdoor living',   'landscaping'],
  ['outdoor kitchen',  'landscaping'],
  ['fire pit',         'landscaping'],
  ['artificial turf',  'landscaping'],
  ['synthetic turf',   'landscaping'],
  ['turf install',     'landscaping'],
  ['retaining wall',   'landscaping'],
  ['french drain',     'landscaping'],
  ['drainage',         'landscaping'],
  ['inground pool',    'landscaping'],
  ['above ground pool','landscaping'],
  ['pool deck',        'landscaping'],
  ['pool heater',      'landscaping'],
  ['hot tub',          'landscaping'],
  ['pergola',          'landscaping'],
  ['gazebo',           'landscaping'],
  ['curb appeal',      'landscaping'],
  ['front yard',       'landscaping'],
  ['low maintenance yard','landscaping'],
  ['tropical vibes yard','landscaping'],
  ['yard situation',   'landscaping'],
  ['landscape quotes', 'landscaping'],
  ['outdoor refresh',  'landscaping'],
  ['privacy fence',    'landscaping'],
  ['privacy hedge',    'landscaping'],
  ['aeration',         'landscaping'],
  ['overseeding',      'landscaping'],
  ['weed control',     'landscaping'],
  ['fertilizing',      'landscaping'],
  ['spring cleanup',   'landscaping'],
  ['fall cleanup',     'landscaping'],
  ['post storm cleanup','landscaping'],
  ['storm cleanup',    'landscaping'],
  ['pressure wash house','landscaping'],
  ['power wash',       'landscaping'],
  ['pressure washing', 'landscaping'],
  ['christmas light installation','landscaping'],
  ['holiday lighting', 'landscaping'],
  ['outdoor lighting', 'landscaping'],
  ['landscape lighting','landscaping'],
  ['sunroom addition', 'landscaping'],
  ['florida room',     'landscaping'],
  ['pool lanai',       'landscaping'],
  ['pool cage addition','landscaping'],
  ['screened patio',   'landscaping'],
  ['covered patio',    'landscaping'],
  ['patio cover',      'landscaping'],

  // Handyman
  ['handyman',        'handyman'],
  ['fix it',          'handyman'],
  ['fix this',        'handyman'],
  ['something broken','handyman'],
  ['install',         'handyman'],
  ['hang',            'handyman'],
  ['mount',           'handyman'],
  ['assembly',        'handyman'],
  ['furniture assembly','handyman'],
  ['tv mount',        'handyman'],
  ['tv mounting',     'handyman'],
  ['drywall',         'handyman'],
  ['patch hole',      'handyman'],
  ['hole in wall',    'handyman'],
  ['caulk',           'handyman'],

  // Roofing
  ['roofing',         'roofing'],
  ['roof',            'roofing'],
  ['shingles',        'roofing'],
  ['gutter',          'roofing'],
  ['gutters',         'roofing'],
  ['roof leak',       'roofing'],
  ['roof is leaking', 'roofing'],
  ['roof repair',     'roofing'],
  ['new roof',        'roofing'],
  ['roofer',          'roofing'],

  // Painting
  ['house painter',    'painting'],
  ['painter',          'painting'],
  ['house painting',   'painting'],
  ['interior paint',   'painting'],
  ['exterior paint',   'painting'],
  ['paint my house',   'painting'],
  ['paint the walls',  'painting'],
  ['paint job',        'painting'],
  ['wall painting',    'painting'],

  // Pest control
  ['pest control',    'pest_control'],
  ['exterminator',    'pest_control'],
  ['roaches',         'pest_control'],
  ['cockroach',       'pest_control'],
  ['cockroaches',     'pest_control'],
  ['roach problem',   'pest_control'],
  ['termites',        'pest_control'],
  ['termite inspection','pest_control'],
  ['bed bugs',        'pest_control'],
  ['bedbugs',         'pest_control'],
  ['rodent',          'pest_control'],
  ['mice',            'pest_control'],
  ['mouse problem',   'pest_control'],
  ['rats',            'pest_control'],
  ['ants',            'pest_control'],
  ['mosquito',        'pest_control'],
  ['mosquitoes',      'pest_control'],
  ['wasps',           'pest_control'],
  ['hornets',         'pest_control'],
  ['infestation',     'pest_control'],
  ['bugs in my house','pest_control'],

  // Locksmith
  ['locked out',       'locksmith'],
  ['locksmith',        'locksmith'],
  ['lock change',      'locksmith'],
  ['lock replacement', 'locksmith'],
  ['lost keys',        'locksmith'],
  ['lost my keys',     'locksmith'],
  ['rekey',            'locksmith'],
  ['cant get in',      'locksmith'],
  ["can't get in",     'locksmith'],
  ['locked out of car','locksmith'],
  ['locked out of house','locksmith'],
  ['locked out of my', 'locksmith'],
  ['key made',         'locksmith'],
  ['duplicate key',    'locksmith'],
  ['deadbolt',         'locksmith'],

  // Dry cleaning / laundry
  ['dry cleaning',    'dry_cleaning'],
  ['dry cleaner',     'dry_cleaning'],
  ['dry clean',       'dry_cleaning'],
  ['dryclean',        'dry_cleaning'],
  ['laundry',         'dry_cleaning'],
  ['wash my clothes', 'dry_cleaning'],
  ['alteration',      'dry_cleaning'],
  ['suit pressed',    'dry_cleaning'],
  ['press my shirt',  'dry_cleaning'],

  // Pool
  ['pool service',    'pool_service'],
  ['pool cleaning',   'pool_service'],
  ['pool repair',     'pool_service'],
  ['pool maintenance','pool_service'],
  ['green pool',      'pool_service'],
  ['cloudy pool',     'pool_service'],
  ['pool guy',        'pool_service'],

  // Flooring
  ['flooring',        'flooring'],
  ['tile',            'flooring'],
  ['carpet',          'flooring'],
  ['hardwood floors', 'flooring'],
  ['laminate floor',  'flooring'],
  ['floor install',   'flooring'],

  // Moving
  ['moving',          'moving'],
  ['moving company',  'moving'],
  ['movers',          'moving'],
  ['help me move',    'moving'],
  ['need movers',     'moving'],
  ['junk removal',    'moving'],
  ['hauling',         'moving'],

  // ══════════════════════════════════════════════════════════════════════════════
  // AUTO
  // ══════════════════════════════════════════════════════════════════════════════

  ['mechanic',           'auto_repair'],
  ['auto repair',        'auto_repair'],
  ['car repair',         'auto_repair'],
  ['car mechanic',       'auto_repair'],
  ['oil change',         'auto_repair'],
  ['brake',              'auto_repair'],
  ['brakes',             'auto_repair'],
  ['tire',               'auto_repair'],
  ['tires',              'auto_repair'],
  ['transmission',       'auto_repair'],
  ['body work',          'auto_repair'],
  ['car detail',         'auto_repair'],
  ['car detailing',      'auto_repair'],
  ['whip broke',         'auto_repair'],
  ['ride broke',         'auto_repair'],
  ['car broke down',     'auto_repair'],
  ['car is making noise','auto_repair'],
  ['check engine light', 'auto_repair'],
  ['engine',             'auto_repair'],
  ['auto body',          'auto_repair'],
  ['collision repair',   'auto_repair'],
  ['dent repair',        'auto_repair'],
  ['windshield',         'auto_repair'],

  ['buy a car',          'auto_dealer'],
  ['buy car',            'auto_dealer'],
  ['used car',           'auto_dealer'],
  ['used cars',          'auto_dealer'],
  ['new car',            'auto_dealer'],
  ['car dealership',     'auto_dealer'],
  ['auto dealer',        'auto_dealer'],
  ['car lot',            'auto_dealer'],
  ['car dealer',         'auto_dealer'],
  ['looking for a car',  'auto_dealer'],
  ['need a car',         'auto_dealer'],

  ['tow truck',          'towing'],
  ['towing',             'towing'],
  ['stranded',           'towing'],
  ['roadside assistance','towing'],
  ['car wont start',     'towing'],
  ["car won't start",    'towing'],
  ['dead battery',       'towing'],
  ['jump start',         'towing'],
  ['flat tire',          'towing'],

  ['gas station',        'gas_station'],
  ['gas up',             'gas_station'],
  ['fill up',            'gas_station'],
  ['fill up my tank',    'gas_station'],
  ['running on e',       'gas_station'],
  ['running on empty',   'gas_station'],
  ['tank is empty',      'gas_station'],
  ['almost out of gas',  'gas_station'],
  ['out of gas',         'gas_station'],
  ['fuel',               'gas_station'],
  ['gas near',           'gas_station'],
  ['cheapest gas',       'gas_station'],

  ['car wash',           'car_wash'],
  ['car washing',        'car_wash'],
  ['wash my car',        'car_wash'],
  ['car needs a wash',   'car_wash'],

  ['car rental',         'car_rental'],
  ['rent a car',         'car_rental'],
  ['rental car',         'car_rental'],
  ['need a rental',      'car_rental'],
  ['enterprise',         'car_rental'],
  ['hertz',              'car_rental'],

  // ══════════════════════════════════════════════════════════════════════════════
  // MEDICAL / HEALTH
  // ══════════════════════════════════════════════════════════════════════════════

  ['doctor',             'clinic'],
  ['doctors',            'clinic'],
  ['physician',          'clinic'],
  ['urgent care',        'clinic'],
  ['walk in clinic',     'clinic'],
  ['walk-in clinic',     'clinic'],
  ['need a doctor',      'clinic'],
  ['sick',               'clinic'],
  ['feel sick',          'clinic'],
  ['feeling sick',       'clinic'],
  ['not feeling well',   'clinic'],
  ['something is wrong', 'clinic'],
  ['stomach hurts',      'clinic'],
  ['headache',           'clinic'],
  ['fever',              'clinic'],
  ['flu',                'clinic'],
  ['strep throat',       'clinic'],
  ['ear infection',      'clinic'],
  ['primary care',       'clinic'],
  ['family doctor',      'clinic'],
  ['clinic near',        'clinic'],

  ['dentist',            'dentist'],
  ['dental',             'dentist'],
  ['tooth hurts',        'dentist'],
  ['toothache',          'dentist'],
  ['tooth pain',         'dentist'],
  ['cracked tooth',      'dentist'],
  ['broken tooth',       'dentist'],
  ['dental cleaning',    'dentist'],
  ['cavity',             'dentist'],
  ['wisdom teeth',       'dentist'],
  ['braces',             'dentist'],
  ['teeth whitening',    'dentist'],

  ['vet',                'veterinary'],
  ['veterinarian',       'veterinary'],
  ['pet sick',           'veterinary'],
  ['dog sick',           'veterinary'],
  ['cat sick',           'veterinary'],
  ['my dog is sick',     'veterinary'],
  ['my cat is sick',     'veterinary'],
  ['dog needs shots',    'veterinary'],
  ['pet emergency',      'veterinary'],
  ['animal hospital',    'veterinary'],
  ['spay',               'veterinary'],
  ['neuter',             'veterinary'],
  ['pet grooming',       'veterinary'],

  ['pharmacy',           'pharmacy'],
  ['prescription',       'pharmacy'],
  ['meds',               'pharmacy'],
  ['medicine',           'pharmacy'],
  ['pick up meds',       'pharmacy'],
  ['pick up prescription','pharmacy'],

  ['plastic surgeon',    'plastic_surgery'],
  ['plastic surgery',    'plastic_surgery'],
  ['breast augmentation','plastic_surgery'],
  ['breast implants',    'plastic_surgery'],
  ['rhinoplasty',        'plastic_surgery'],
  ['nose job',           'plastic_surgery'],
  ['tummy tuck',         'plastic_surgery'],
  ['liposuction',        'plastic_surgery'],
  ['botox',              'plastic_surgery'],
  ['filler',             'plastic_surgery'],
  ['lip filler',         'plastic_surgery'],
  ['bbl',                'plastic_surgery'],
  ['mommy makeover',     'plastic_surgery'],
  ['facelift',           'plastic_surgery'],

  ['dermatologist',      'dermatology'],
  ['skin care',          'dermatology'],
  ['skin doctor',        'dermatology'],
  ['medspa',             'dermatology'],
  ['med spa',            'dermatology'],
  ['laser treatment',    'dermatology'],
  ['coolsculpting',      'dermatology'],
  ['acne treatment',     'dermatology'],
  ['mole removal',       'dermatology'],

  // ══════════════════════════════════════════════════════════════════════════════
  // PROFESSIONAL SERVICES
  // ══════════════════════════════════════════════════════════════════════════════

  ['lawyer',          'law_firm'],
  ['attorney',        'law_firm'],
  ['legal help',      'law_firm'],
  ['legal advice',    'law_firm'],
  ['lawsuit',         'law_firm'],
  ['court date',      'law_firm'],
  ['got a case',      'law_firm'],
  ['need a lawyer',   'law_firm'],
  ['getting sued',    'law_firm'],
  ['divorce lawyer',  'law_firm'],
  ['injury lawyer',   'law_firm'],
  ['criminal lawyer', 'law_firm'],
  ['estate planning', 'law_firm'],
  ['notary',          'law_firm'],

  ['accountant',      'accounting'],
  ['tax prep',        'accounting'],
  ['bookkeeping',     'accounting'],
  ['cpa',             'accounting'],
  ['accounting',      'accounting'],

  ['taxes',           'tax_advisor'],
  ['tax return',      'tax_advisor'],
  ['file taxes',      'tax_advisor'],
  ['do my taxes',     'tax_advisor'],
  ['tax help',        'tax_advisor'],
  ['irs',             'tax_advisor'],

  ['insurance',       'insurance'],
  ['insure',          'insurance'],
  ['insurance agent', 'insurance'],
  ['home insurance',  'insurance'],
  ['car insurance',   'insurance'],
  ['life insurance',  'insurance'],
  ['health insurance','insurance'],

  ['financial advisor','financial_advisor'],
  ['retirement',       'financial_advisor'],
  ['invest',           'financial_advisor'],
  ['investing',        'financial_advisor'],
  ['wealth management','financial_advisor'],
  ['financial planner','financial_advisor'],
  ['stock broker',     'financial_advisor'],

  // ══════════════════════════════════════════════════════════════════════════════
  // FINANCE / BANKING
  // ══════════════════════════════════════════════════════════════════════════════

  ['atm',             'bank'],
  ['nearest atm',     'bank'],
  ['cash machine',    'bank'],
  ['need cash',       'bank'],
  ['get cash',        'bank'],
  ['withdraw cash',   'bank'],
  ['bank near',       'bank'],
  ['bank',            'bank'],
  ['credit union',    'bank'],
  ['open account',    'bank'],

  // ══════════════════════════════════════════════════════════════════════════════
  // REAL ESTATE
  // ══════════════════════════════════════════════════════════════════════════════

  ['realtor',               'real_estate'],
  ['real estate',           'real_estate'],
  ['real estate agent',     'real_estate'],
  ['home buying',           'real_estate'],
  ['buy a house',           'real_estate'],
  ['buy a home',            'real_estate'],
  ['sell my home',          'real_estate'],
  ['sell my house',         'real_estate'],
  ['properties for rent',   'real_estate'],
  ['apartment for rent',    'real_estate'],
  ['rental property',       'real_estate'],
  ['looking for a house',   'real_estate'],
  ['house for rent',        'real_estate'],
  ['apartment near',        'real_estate'],
  ['condo for rent',        'real_estate'],
  ['home listing',          'real_estate'],

  // ══════════════════════════════════════════════════════════════════════════════
  // FITNESS / GYM
  // ══════════════════════════════════════════════════════════════════════════════

  ['gym',             'gym'],
  ['fitness',         'gym'],
  ['fitness center',  'gym'],
  ['fitness centre',  'gym'],
  ['workout',         'gym'],
  ['work out',        'gym'],
  ['work out near',   'gym'],
  ['where can i work out', 'gym'],
  ['where to work out','gym'],
  ['want to work out','gym'],
  ['lift weights',    'gym'],
  ['weightlifting',   'gym'],
  ['crossfit',        'gym'],
  ['yoga',            'gym'],
  ['pilates',         'gym'],
  ['personal trainer','gym'],
  ['personal training','gym'],
  ['get swole',       'gym'],
  ['hit the gym',     'gym'],
  ['gym near',        'gym'],
  ['planet fitness',  'gym'],
  ['24 hour fitness', 'gym'],
  ['anytime fitness', 'gym'],
  ['ymca',            'gym'],
  ['spin class',      'gym'],
  ['zumba',           'gym'],
  ['boxing gym',      'gym'],
  ['mma gym',         'gym'],
  ['martial arts',    'gym'],
  ['swim laps',       'gym'],
  ['lap pool',        'gym'],
  // Fitness / sports gear slang
  ['dumbbells',        'gym'],
  ['resistance bands', 'gym'],
  ['exercise mat',     'gym'],
  ['foam roller',      'gym'],
  ['massage gun',      'gym'],
  ['agility ladder',   'gym'],
  ['jump rope',        'gym'],
  ['protein powder',   'gym'],
  ['protein supplement','gym'],
  ['pre workout',      'gym'],
  ['creatine',         'gym'],
  ['sports nutrition', 'gym'],
  ['yoga mat',         'gym'],
  ['pilates princess', 'gym'],
  ['that girl workout','gym'],
  ['band work',        'gym'],
  ['agility ladder sesh','gym'],
  ['bulk season',      'gym'],
  ['cut season',       'gym'],
  ['gains',            'gym'],
  ['gym rat',          'gym'],
  ['get gains',        'gym'],
  ['new gym',          'gym'],
  ['looking for a gym','gym'],
  ['gym membership',   'gym'],
  ['swimming pool',    'gym'],
  ['swim class',       'gym'],
  ['aqua fitness',     'gym'],

  // ══════════════════════════════════════════════════════════════════════════════
  // HOTEL / LODGING
  // ══════════════════════════════════════════════════════════════════════════════

  ['hotel',            'hotel'],
  ['motel',            'hotel'],
  ['place to stay',    'hotel'],
  ['place to crash',   'hotel'],
  ['somewhere to stay','hotel'],
  ['somewhere to sleep','hotel'],
  ['crash for the night','hotel'],
  ['lay my head',      'hotel'],
  ['need a room',      'hotel'],
  ['book a room',      'hotel'],
  ['airbnb',           'hotel'],
  ['vacation rental',  'hotel'],
  ['extended stay',    'hotel'],
  ['hotel near',       'hotel'],
  ['cheap hotel',      'hotel'],
  ['hotel tonight',    'hotel'],
  ['last minute hotel','hotel'],

  // ══════════════════════════════════════════════════════════════════════════════
  // RETAIL / SHOPPING
  // ══════════════════════════════════════════════════════════════════════════════

  // Clothes / apparel
  ['clothing store',  'clothes'],
  ['clothes',         'clothes'],
  ['apparel',         'clothes'],
  ['shoes',           'clothes'],
  ['sneakers',        'clothes'],
  ['new kicks',       'clothes'],
  ['fresh sneakers',  'clothes'],
  ['boots',           'clothes'],
  ['boot season',     'clothes'],
  ['suit',            'clothes'],
  ['tailor',          'clothes'],
  ['tuxedo',          'clothes'],
  ['alterations',     'clothes'],
  ['chef shoes',      'clothes'],
  ['work shoes',      'clothes'],
  ['chef uniform',    'clothes'],
  ['dress',           'clothes'],
  ['jeans',           'clothes'],
  ['outfit',          'clothes'],
  ['shopping for clothes','clothes'],
  ['something to wear','clothes'],
  ['need an outfit',  'clothes'],
  // Women's fashion slang
  ['new fit',         'clothes'],
  ['new fits',        'clothes'],
  ['fresh threads',   'clothes'],
  ['wardrobe refresh','clothes'],
  ['glow-up clothes', 'clothes'],
  ['comfy but cute',  'clothes'],
  ['that girl outfit','clothes'],
  ['that girl vibe',  'clothes'],
  ['coquette outfit', 'clothes'],
  ['coquette dress',  'clothes'],
  ['amazon haul',     'clothes'],
  ['amazon finds',    'clothes'],
  ['amazon fashion',  'clothes'],
  ['vacation fits',   'clothes'],
  ['vacation outfit', 'clothes'],
  ['back to school haul','clothes'],
  ['summer slay',     'clothes'],
  ['fit check',       'clothes'],
  ['haul',            'clothes'],
  ['leggings',        'clothes'],
  ['athleisure',      'clothes'],
  ['athleisure set',  'clothes'],
  ['wide leg pants',  'clothes'],
  ['palazzo pants',   'clothes'],
  ['linen pants',     'clothes'],
  ['maxi dress',      'clothes'],
  ['mini dress',      'clothes'],
  ['romper',          'clothes'],
  ['jumpsuit',        'clothes'],
  ['pajamas',         'clothes'],
  ['loungewear',      'clothes'],
  ['swimwear',        'clothes'],
  ['bikini',          'clothes'],
  ['gym shorts',      'clothes'],
  ['compression shorts','clothes'],
  ['joggers',         'clothes'],
  ['hoodies',         'clothes'],
  ['sweatshirt',      'clothes'],
  ['cardigan',        'clothes'],
  ['workout set',     'clothes'],
  ['matching workout set','clothes'],
  ['daily uniform',   'clothes'],
  ['gym drip',        'clothes'],
  ['boxer briefs',    'clothes'],
  ['mens underwear',  'clothes'],
  ['polo shirt',      'clothes'],
  ['chinos',          'clothes'],
  ['cargo pants',     'clothes'],
  ['bomber jacket',   'clothes'],
  ['flannel',         'clothes'],
  ['dress shirt',     'clothes'],
  ['swim trunks',     'clothes'],
  ['basic tees',      'clothes'],
  ['graphic tee',     'clothes'],
  ['oversized tee',   'clothes'],
  ['linen set',       'clothes'],
  ['dupe outfit',     'clothes'],
  ['looks expensive but cheap','clothes'],
  ['copped some gear','clothes'],
  ['copped new kicks','clothes'],
  ['upgrade my wardrobe','clothes'],
  ['need new clothes','clothes'],
  ['something cute to wear','clothes'],
  ['clothes shopping','clothes'],
  ['fashion store',   'clothes'],
  ['boutique',        'clothes'],

  // Grocery
  ['grocery store',   'grocery'],
  ['grocery',         'grocery'],
  ['groceries',       'grocery'],
  ['supermarket',     'grocery'],
  ['publix',          'grocery'],
  ['walmart',         'grocery'],
  ['target',          'grocery'],
  ['aldi',            'grocery'],
  ['kroger',          'grocery'],
  ['whole foods',     'grocery'],
  ['fresh market',    'grocery'],
  ['produce',         'grocery'],
  ['milk',            'grocery'],
  ['eggs',            'grocery'],
  ['bread',           'grocery'],
  ['groceries near',  'grocery'],
  ['food shopping',   'grocery'],

  // Furniture / home
  ['furniture',    'furniture'],
  ['mattress',     'furniture'],
  ['sofa',         'furniture'],
  ['couch',        'furniture'],
  ['bed frame',    'furniture'],
  ['furniture store','furniture'],
  ['home goods',   'furniture'],

  // Jewelry
  ['jewelry',         'jewelry'],
  ['jeweler',         'jewelry'],
  ['diamond',         'jewelry'],
  ['necklace',        'jewelry'],
  ['engagement ring', 'jewelry'],
  ['bracelet',        'jewelry'],
  ['earrings',        'jewelry'],
  ['wedding ring',    'jewelry'],
  ['jewelry store',   'jewelry'],

  // Electronics
  ['electronics',      'electronics'],
  ['phone repair',     'electronics'],
  ['phone screen',     'electronics'],
  ['cracked screen',   'electronics'],
  ['laptop repair',    'electronics'],
  ['laptop',           'electronics'],
  ['computer repair',  'electronics'],
  ['iphone repair',    'electronics'],
  ['samsung repair',   'electronics'],
  ['electronics store','electronics'],
  ['best buy',         'electronics'],
  ['best buy run',     'electronics'],
  ['best buy deal',    'electronics'],
  // Tech/electronics slang
  ['oled tv',          'electronics'],
  ['new tv',           'electronics'],
  ['tv setup',         'electronics'],
  ['gaming setup',     'electronics'],
  ['gaming rig',       'electronics'],
  ['ps5',              'electronics'],
  ['playstation',      'electronics'],
  ['xbox',             'electronics'],
  ['gaming pc',        'electronics'],
  ['steam deck',       'electronics'],
  ['gaming monitor',   'electronics'],
  ['mechanical keyboard','electronics'],
  ['gaming mouse',     'electronics'],
  ['gaming headset',   'electronics'],
  ['gaming chair',     'electronics'],
  ['soundbar',         'electronics'],
  ['bluetooth speaker','electronics'],
  ['wireless earbuds', 'electronics'],
  ['airpods',          'electronics'],
  ['noise cancelling headphones','electronics'],
  ['macbook',          'electronics'],
  ['ipad',             'electronics'],
  ['iphone',           'electronics'],
  ['samsung galaxy',   'electronics'],
  ['google pixel',     'electronics'],
  ['apple watch',      'electronics'],
  ['smart watch',      'electronics'],
  ['power bank',       'electronics'],
  ['portable charger', 'electronics'],
  ['vr headset',       'electronics'],
  ['meta quest',       'electronics'],
  ['smart home',       'electronics'],
  ['ring doorbell',    'electronics'],
  ['battlestation',    'electronics'],
  ['desk setup',       'electronics'],
  ['rgb setup',        'electronics'],
  ['monitor upgrade',  'electronics'],
  ['copped a new',     'electronics'],
  ['upgraded the',     'electronics'],
  ['new headset',      'electronics'],
  ['payday haul tech', 'electronics'],
  ['setup upgrade',    'electronics'],
  ['record player',    'electronics'],
  ['turntable',        'electronics'],
  ['car audio',        'electronics'],
  ['car speakers',     'electronics'],

  // Hardware
  ['hardware store',  'hardware'],
  ['home depot',      'hardware'],
  ['lowes',           'hardware'],
  ["lowe's",          'hardware'],
  ['tools',           'hardware'],
  ['hardware',        'hardware'],
  ['lumber',          'hardware'],
  ['ryobi',           'hardware'],
  ['dewalt',          'hardware'],
  ['milwaukee tool',  'hardware'],
  ['power drill',     'hardware'],
  ['cordless drill',  'hardware'],
  ['circular saw',    'hardware'],
  ['miter saw',       'hardware'],
  ['pressure washer', 'hardware'],
  ['lawn mower',      'hardware'],
  ['leaf blower',     'hardware'],
  ['weed eater',      'hardware'],
  ['string trimmer',  'hardware'],
  ['chainsaw',        'hardware'],
  ['paint roller',    'hardware'],
  ['paint sprayer',   'hardware'],
  ['drywall sheets',  'hardware'],
  ['concrete mix',    'hardware'],
  ['quikrete',        'hardware'],
  ['plywood',         'hardware'],
  ['pvc pipe',        'hardware'],
  ['tool rental',     'hardware'],
  ['equipment rental','hardware'],
  ['rent tools',      'hardware'],
  ['weekend project', 'hardware'],
  ['diy project',     'hardware'],
  ['home repair supplies','hardware'],
  ['ace hardware',    'hardware'],
  ['deck screws',     'hardware'],
  ['garage shelving', 'hardware'],
  ['tool organizer',  'hardware'],
  ['pegboard',        'hardware'],
  ['generator',       'hardware'],
  ['step ladder',     'hardware'],
  ['extension ladder','hardware'],
  ['safety glasses',  'hardware'],
  ['work gloves',     'hardware'],
  ['knee pads',       'hardware'],
  ['tool combo kit',  'hardware'],
  ['cordless kit',    'hardware'],
  ['spring tool sale','hardware'],
  ['tool clearance',  'hardware'],

  // ══════════════════════════════════════════════════════════════════════════════
  // CHILDCARE
  // ══════════════════════════════════════════════════════════════════════════════

  ['daycare',       'childcare'],
  ['day care',      'childcare'],
  ['babysitter',    'childcare'],
  ['babysitting',   'childcare'],
  ['nanny',         'childcare'],
  ['preschool',     'childcare'],
  ['after school',  'childcare'],
  ['childcare',     'childcare'],
  ['drop off kids', 'childcare'],
  ['watch my kids', 'childcare'],
  ['watch my child','childcare'],

  // ══════════════════════════════════════════════════════════════════════════════
  // OTHER SERVICES
  // ══════════════════════════════════════════════════════════════════════════════

  ['florist',       'florist'],
  ['flowers',       'florist'],
  ['flower shop',   'florist'],
  ['flower delivery','florist'],
  ['bouquet',       'florist'],
  ['send flowers',  'florist'],

  ['tattoo',        'tattoo'],
  ['tattoo shop',   'tattoo'],
  ['tattoo artist', 'tattoo'],
  ['tattoo parlor', 'tattoo'],
  ['get a tattoo',  'tattoo'],
  ['ink',           'tattoo'],

  ['storage unit',  'storage'],
  ['self storage',  'storage'],
  ['storage near',  'storage'],
  ['need storage',  'storage'],

  ['museum',        'museum'],
  ['art museum',    'museum'],
  ['history museum','museum'],
  ['things to do',  'museum'],
  ['something to do','museum'],

  ['eye doctor',    'optician'],
  ['glasses',       'optician'],
  ['optician',      'optician'],
  ['contact lenses','optician'],
  ['eye exam',      'optician'],
  ['eye glasses',   'optician'],
  ['vision',        'optician'],

  // ══════════════════════════════════════════════════════════════════════════════
  // SLANG / DIALECT / CASUAL SPEECH
  // "Talk to it like a buddy"
  // ══════════════════════════════════════════════════════════════════════════════

  // Food slang
  ['where we eating',      'restaurant'],
  ['what spot',            'restaurant'],
  ['pull up somewhere',    'restaurant'],
  ['take me somewhere to eat','restaurant'],
  ['tryna get food',       'restaurant'],
  ['tryna grab food',      'restaurant'],
  ['need some grub',       'restaurant'],
  ['where the food at',    'restaurant'],
  ["what's good to eat",   'restaurant'],
  ["what's open to eat",   'restaurant'],
  ['dead ass hungry',      'restaurant'],
  ['lowkey hungry',        'restaurant'],
  ['bro i need food',      'restaurant'],
  ['fam i need food',      'restaurant'],
  ['starving rn',          'restaurant'],
  ['dying of hunger',      'restaurant'],

  // Drink slang
  ['pull up to the bar',   'bar'],
  ['hit the bar',          'bar'],
  ['lets get drinks',      'bar'],
  ["let's get drinks",     'bar'],
  ['where we drinking',    'bar'],
  ['where the drinks at',  'bar'],
  ['need a vibe',          'bar'],
  ['where the vibes',      'bar'],
  ['going out',            'bar'],
  ['drinks tonight',       'bar'],
  ['shots',                'bar'],
  ['wanna get drinks',     'bar'],

  // Auto slang
  ['whip is messed up',    'auto_repair'],
  ['whip broke down',      'auto_repair'],
  ['my whip aint right',   'auto_repair'],
  ['get my ride fixed',    'auto_repair'],
  ['my ride is busted',    'auto_repair'],
  ['car acting up',        'auto_repair'],
  ['car on e',             'gas_station'],
  ['gas me up',            'gas_station'],

  // Plumbing slang
  ['water everywhere',     'plumber'],
  ['toilet is wilding',    'plumber'],
  ['pipes acting crazy',   'plumber'],
  ['bathroom flooded',     'plumber'],

  // Beauty slang
  ['looking raggedy',      'beauty'],
  ['need to be fixed up',  'beauty'],
  ['glow up',              'beauty'],
  ['glow-up',              'beauty'],
  ['drip',                 'beauty'],
  ['slay',                 'beauty'],
  ['snatched',             'beauty'],
  ['skincare girly',       'beauty'],
  ['holy grail',           'beauty'],
  ['glass skin',           'beauty'],
  ['that girl routine',    'beauty'],
  ['self care goodies',    'beauty'],
  ['clean girl',           'beauty'],
  ['sephora',              'beauty'],
  ['ulta',                 'beauty'],
  ['beauty haul',          'beauty'],
  ['skincare haul',        'beauty'],
  ['sephora haul',         'beauty'],
  ['full restock',         'beauty'],
  ['monthly maintenance',  'beauty'],
  ['glow-up kit',          'beauty'],
  ['shelfie',              'beauty'],
  // Collector card slang → retail
  ['trading cards',        'retail'],
  ['pokemon cards',        'retail'],
  ['sports cards',         'retail'],
  ['collector cards',      'retail'],
  ['booster pack',         'retail'],
  ['booster box',          'retail'],
  ['ripping packs',        'retail'],
  ['pack rip',             'retail'],
  ['chase card',           'retail'],
  ['graded card',          'retail'],
  ['psa 10',               'retail'],
  ['box break',            'retail'],
  ['card shop',            'retail'],
  ['card store',           'retail'],
  ['hobby shop',           'retail'],
  // Sports equipment → gym or retail
  ['cleats',               'retail'],
  ['soccer cleats',        'retail'],
  ['football cleats',      'retail'],
  ['basketball shoes',     'retail'],
  ['high tops',            'retail'],
  ['running shoes',        'retail'],
  ['track spikes',         'retail'],
  ['tennis racket',        'retail'],
  ['pickleball paddle',    'retail'],
  ['golf clubs',           'retail'],
  ['golf balls',           'retail'],
  ['golf bag',             'retail'],
  ['swim goggles',         'retail'],
  ['sports equipment',     'retail'],
  ['sporting goods',       'retail'],
  ['sports store',         'retail'],
  ['dicks sporting',       'retail'],
  ['new gear drop',        'retail'],
  ['fresh kit',            'retail'],
  ['gear check',           'retail'],
  ['full kit refresh',     'retail'],

  // Hotel slang
  ['need somewhere to post up','hotel'],
  ['where can i post up',  'hotel'],
  ['need a spot to sleep', 'hotel'],

  // Network infrastructure / timing (Syncworks)
  ['ntp server',           'network_infrastructure'],
  ['ptp grandmaster',      'network_infrastructure'],
  ['network timing',       'network_infrastructure'],
  ['synchronization',      'network_infrastructure'],
  ['gnss',                 'network_infrastructure'],
  ['timing infrastructure','network_infrastructure'],
  ['5g timing',            'network_infrastructure'],
  ['bits infrastructure',  'network_infrastructure'],
  ['cran timing',          'network_infrastructure'],
  ['telecom timing',       'network_infrastructure'],
  ['time server',          'network_infrastructure'],
  ['network sync',         'network_infrastructure'],

  // Startup accelerator (AcceleratePV)
  ['startup accelerator',  'startup_accelerator'],
  ['pitch prep',           'startup_accelerator'],
  ['demo day',             'startup_accelerator'],
  ['medtech accelerator',  'startup_accelerator'],
  ['healthtech startup',   'startup_accelerator'],
  ['femtech',              'startup_accelerator'],
  ['founder program',      'startup_accelerator'],
  ['accelerator program',  'startup_accelerator'],

  // Venture studio (Silicon Beach AI)
  ['venture studio',       'venture_studio'],
  ['startup studio',       'venture_studio'],
  ['series a prep',        'venture_studio'],
  ['go-to-market startup', 'venture_studio'],
  ['pitch development',    'venture_studio'],
  ['fundraising support',  'venture_studio'],
  ['commercialization strategy','venture_studio'],

  // Locksmith slang
  ['locked out my crib',   'locksmith'],
  ['locked out my car',    'locksmith'],
  ['left my keys inside',  'locksmith'],
  ['keys locked in',       'locksmith'],
];

// ── REQUEST_PHRASES: signals user wants a service (not a name search) ─────────
const REQUEST_PHRASES = [
  'i need','i want','i have a','fix my','fix the','repair my','repair the',
  'find me a','find me an','get me a','get me an','looking for a','looking for an',
  'need a','need an','need some','need someone','need help','help me','can someone',
  'who can','who does','where can i','where do i','where is a','where is the',
  'how do i','can i get','can i find','can i buy',
  'looking to get','trying to find','tryna find','tryna get','gotta get',
  'my .+ is broken','my .+ is leaking','my .+ is not working',
  'broken','not working','clogged','flooded',
  'i am hungry','im hungry','i\'m hungry','i am starving','im starving',
  'where should i','where to','where we','what spot',
];

// ── resolve(query) → { cat, expanded } or null ────────────────────────────────
function resolve(query) {
  const lower = (query || '').toLowerCase().trim();
  if (!lower) return null;
  // Longest match wins — sort once at call time
  // (array is ~300 entries, negligible overhead)
  const sorted = [...KEYWORD_MAP].sort((a, b) => b[0].length - a[0].length);
  for (const [kw, cat] of sorted) {
    if (lower.includes(kw)) {
      return { cat, expanded: CAT_EXPAND[cat] || [cat] };
    }
  }
  return null;
}

// ── isServiceRequest(query) → boolean ─────────────────────────────────────────
const _REQ_RE = new RegExp(REQUEST_PHRASES.join('|'), 'i');
function isServiceRequest(query) {
  return _REQ_RE.test((query || '').toLowerCase());
}

// ── expandCat(cat) → string[] of real DB categories ──────────────────────────
function expandCat(cat) {
  return CAT_EXPAND[cat] || [cat];
}

module.exports = {
  resolve, isServiceRequest, expandCat,
  getCTAType, CTA_PROMPTS,
  CAT_EXPAND, KEYWORD_MAP, DB_CATS,
  COME_TO_ME_CATS, APPOINTMENT_CATS, RESERVATION_CATS,
};
